### ISSUE TITLE
ar71xx patch

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#11]
Sollen wir den patch übernehmen?

https://github.com/freifunk-gluon/gluon/commit/59a9ea197844c5c68417682da4b4d7a448b51428

**Comment by RubenKelevra** [comment]
@kaechele? :)

**Comment by kaechele** [comment]
Solange der "workaround" patch funktioniert würde ich da nicht an die Knöppe packen, da wir uns sonst unschön vom upstream branch entfernen und uns die merges kaputtmachen.

**Comment by RubenKelevra** [comment]
okay
