### ISSUE TITLE
Enable ECN on Nodes

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#44]

**Comment by kevin-olbrich** [comment]
Laut OpenWRT-Doku sollten wir das nicht tun. Möchtest du das auf der Public-SSID aktivieren und auf dem Gateway wieder zurück setzen?

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Nein, rein für den fastd-Traffic. OpenWRT-Doku ist immer konsevativ... wo genau steht das denn?

**Comment by kevin-olbrich** [comment]
https://dev.openwrt.org/ticket/3001

Da wir das nur intern machen, ist das in Ordnung. Aber bringt uns das denn überhaupt etwas?

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Feature-Request bei Fastd eingericht, da UDP kein ECN kann, müsste das bei Fastd implementiert werden.
