### ISSUE TITLE
Setzen von basic und supported rates + require-mode 

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#52]
... damit die Endgeräte nicht so lange auf den 1 MBit-Verbindungen kleben bleiben.

Erlauben sollten wir alle G-Raten

list supported_rates '6000 9000 12000 18000 24000 36000 48000 54000'

Basic-Rates enthalten 6 MBit und alle Raten mit 3/4 Kodier-Effizienz.

list basic_rate '6000 9000 18000 36000 54000'

Dieser Patch schließt B-Geräte aus. Hier sollten wir also require_mode auf 'g' setzen, damit der B-Support abgeschaltet wird.

**Comment by kevin-olbrich** [comment]
Kann man dann auf G-Standard trotzdem <54 Rates verwenden?

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Ja. Dieser Patch würde nur das zurückfallen auf 802.11b-Datenraten verhindern.

**Comment by kevin-olbrich** [comment]
Naja, Datenraten klingt jedenfalls nicht korrekt. Oder verstehe ich da was falsch? Jedenfalls sollte der unter 54 MBit meshen und Endgeräte annehmen.

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
6000 ist 6 MBit usw. Angegeben werden nur die Basisraten für G, die N-Raten werden einfach nur von den Basisraten hoch geschaltet. :)

**Comment by RubenKelevra** [comment]
Implemented in https://github.com/VfN-NRW/gluon/commit/89cf170180e8b5c1401ad43de07c37ee76efc988
