### ISSUE TITLE
noscan 

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#53]
Wir sollten noscan einschalten, wir haben in einigen Regionen wo wir quasi auf greenfield senden auf HT20 runter geschaltet mit Gluon, da die Freifunk-Hotspots beim Scan als fremde Hotspots erkannt werden. Also an Stellen wo HT40 sinnvoll wäre, weil dann mehr AirTime zu Verfügung steht, durch den Bandbreiten-Gewinn schalten wir es derzeit ab.

Das ist nicht Standard-Konform, verstößt aber nicht (meines Wissen nach) nicht gegen Regulatorien. Wir stören damit auch nicht im Sinne von stören, da WLAN immer LBT ( listen before talk ) ist, und bei belegtem zweit-Kanal automatisch auf HT20 für den Transmit runter geschaltet wird. 

Dadurch wird der Standard quasi eh eingehalten, da das zuschalten des zweiten Kanals dynamisch erfolgt.

**Comment by kevin-olbrich** [comment]
Halte ich bei 2,4GHz auch für okay. Und da wir wegen mesh eh schlecht Channel-Hopping machen können, bringt das den anderen eh nichts.

IMHO: andere können ja ihre channels wechseln :P

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Meist passiert das sogar, da ja die ganzen Freifunk-Nodes doch einen Haufen WLANs aufspannen. :)

**Comment by kevin-olbrich** [comment]
Die meisten APs haben es eh an, von daher halte ich scannen eh für blöd, dann hoppt jeder ständig.

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
noscan bedeutet nicht, Autochannel abschalten, sondern den im Standard vorgeschrieben Scan der Frequenzen für die Entscheidung ob HT40 aktiviert wird, oder HT20 das Maximum des APs ist.

**Comment by kevin-olbrich** [comment]
Ja, aber die Wahrscheinlichkeit das ein fremder AP hoppt wenn wir HT40 forcen, ist gross genug. Meiner Meinung nach jedenfalls.

Wenn jemand statisch conft ist das halt Pech, bei mesh in der Nähe wird das wohl jemand merken und dann seinen eigenen Channel ändern.

Ich fänd es blöd wenn wir HT20 machen nur weil so eine kaputte Fritte nicht weg springt.

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Naja Fritzbox, Asus und Speedport erkennen eh nur den Primary der anderen, würden uns also egal ob mit oder ohne Scan auf jeden Fall in den Zweit-Channel springen. 

Das einzige das Verhalten zu umgehen ist, den eigenen Router auf Channel 13 fest zu pappen.

Größtes Problem ist eigentlich nicht, dass wir unbedingt noscan wegen den anderen Routern brauchen sondern der Scan unsere Nodes als "Störquellen" erkennt und HT20 aktiviert.

**Comment by RubenKelevra** [comment]
Wurde in https://github.com/VfN-NRW/gluon/commit/81e6501a60ba2352d9f04e1b770d1735a87fdc28 (next-branch) und https://github.com/VfN-NRW/gluon/commit/879320a196e03bb3ca4fc3ef46671f93c70a386c (after-next) inkludiert.
