### ISSUE TITLE
Text muss angepasst werden

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#67]
"Geh auf die Registrierungsseite und sag uns wie man dich erreicht, wenn es mal technische Probleme mit deinem Freifunk-Knoten gibt."

**Comment by grmp** [comment]
Wo genau taucht das auf?
Fehlt die Übersetzung oder was ist das Problem?

**Comment by RubenKelevra** [comment]
This issue was moved to VfN-NRW/gluon-firmware-builder#31
