### ISSUE TITLE
802.11r support? Ist das interessant?

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#84]

**Comment by RubenKelevra** [comment]
Vollkommen unbekannt. War ne Notiz an mich, falls ich mal Langeweile hab. :)

**Comment by bitnukl** [comment]
Nach meinem Wissen bringt das genau nichts, wenn das Netz nicht WPA-PSK oder WPA-Enterprise gesichert ist. 

Gruß
Robert

**Comment by RubenKelevra** [comment]
Ja, dachte ans Privatnetz. :)

**Comment by RubenKelevra** [comment]
This issue was moved to VfN-NRW/gluon-firmware-builder#25
