### ISSUE TITLE
test scp / sftp support (via curl?) for transmitting binary diffs

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon#91]

**Comment by RubenKelevra** [comment]
Something like

curl -s --hostpubmd5 123123123 -T /tmp/nodestats-20151126-114050-289193-28193723918823 sftp://nodestats@server.vfn-nrw.de:1337/upload/

**Comment by kevin-olbrich** [comment]
Für gut befunden ;-)

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Idee verworfen.

**Comment by RubenKelevra** [comment]
This issue was moved to VfN-NRW/gluon-firmware-builder#23
