### ISSUE TITLE
Nativ Gluon sysupgrade to VfN-Gluon does not preserve coords-submit field

### ISSUE THREAD

**Issue by ulfkreutzberg** [VfN-NRW/gluon#95]
Nach `sysupgrade <imgname>` werden im UI die Koordinaten nicht angezeigt (Haken "enter koordinates" ist nicht angehakt, falls vorher aktiv). Per `uci show gluon-node-info` ist aber alles vorhanden, und der node wird auch auf der map angezeigt. Wird also vom UI nicht richtig dargestellt.

**Comment by RubenKelevra** [comment]
Nicht reproduzierbar, falls es erneut auftritt bitte neu öffnen.

**Comment by RubenKelevra** [comment]
This issue was moved to VfN-NRW/gluon-firmware-builder#19
